image:
  file: .gitpod.Dockerfile
tasks:
  - init: > 
      yarn install && 
      ./scripts/install-deps.js &&
      ./scripts/build-native.js &&
      yarn run build
    command: yarn run start

ports: 
  - port: 3000
    onOpen: open-preview